apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-170538274
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-170538274
    app.kubernetes.io/part-of: test-app-170538274
  name: python-basic-170538274
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-basic-170538274
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-basic-170538274
    spec:
      containers:
      - image: quay.io/hacdev/viqoh7o2-tenant/test-app-170538274/python-basic-170538274@sha256:2c82f331c970ee973e948c9d63acbb647a0f4feb27a3fc7cfcb660562038f462
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
