apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-170538274
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-170538274
    app.kubernetes.io/part-of: test-app-170538274
  name: python-basic-170538274
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: python-basic-170538274
status:
  loadBalancer: {}
